// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtlalqcuufxewrkputzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0bGFscWN1dWZ4ZXdya3B1dHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDc4ODYsImV4cCI6MjA3MjQyMzg4Nn0.eaF49nZ8cf_vxkJhECqvMfGa6hTK5ahf5Zb4xIJm2bM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,   // IMPORTANT for magic-link hash
    flowType: 'implicit'        // hash-based (#access_token) flow
  }
});